---
title: "Facial Recognition"
author: "Andrea R Seisler"
date: "`r Sys.time()`"
output: 
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
---

# Coding [Facial Recognition](facial-recognition.Rmd)

Coding will be completed using [Datavyu](http://datavyu.org/)

## momhead

`<momhead-m>`

### General Orientation

This code captures the times that the mom head or any part of the head is in the video frame. 
Times when the head is in view are scored as events, where the gray spaces between cells mean the head is out of view.

Coders are watching/tagging each of these events by marking onset/offset times for the duration of time the mom head is within the viewing frame.

### Value List

`m` = mom head in video

### Operational Definitions

`<m>` Code "m" when any part of the mom head is in the video frame

### How to Code

Set “JUMP-BACK-BY” key to 1 s.

Enable cell highlighting on the controller.

Watch in real time for the mom's movement. As soon as you see mom's head in the frame; hit #5-STOP and then hit “JUMP-BACK-BY” to go back to the timestamp that is just before the mom's head appears in the frame. 

Hit ENTER to create a new cell at this Onset.

Now, watch in real time to see when the mom head is out of the frame. 
The Offset is when the mom head is out of the frame least 0.5 s

To set the Offset, use the same rules for mechanics as with the Onset. 
Hit #5-STOP and then hit “JUMP-BACK-BY” to go back to the timestamp that is just before the head exits the frame. 
Then JOG forward by hitting #3-JOGFORWARD until you reach the Offset of that cell. 
If you go too far, you can JOG backward by hitting #1-JOGBACK. 
You will likely have to hit the JOG keys numerous times. 
If you feel that you have either jumped too far back or went too far forward, hold the JOG keys to move in either direction a bit faster.

Hit ???? to create the Offset

### Create momangle column

run the ??? script to create a new column for momangle


## babyhead

`<babyhead-b>`

### General Orientation

This code captures the times that the baby head or any part of the head is in the video frame. 

Times when the head is in view are scored as events, where the gray spaces between cells mean the head is out of view.

Coders are watching/tagging each of these events by marking onset/offset times for the duration of time the mom head is within the viewing frame.

### Value List

`b` = baby head in video

### Operational Definitions

`<b>` Code "b" when any part of the baby head is in the video frame

### How to Code

Set “JUMP-BACK-BY” key to 1 s.

Enable cell highlighting on the controller.

Watch in real time for the baby's movement. As soon as you see baby's head in the frame; hit #5-STOP and then hit “JUMP-BACK-BY” to go back to the timestamp that is just before the baby's head appears in the frame. 

Hit ENTER to create a new cell at this Onset.

Now, watch in real time to see when the baby head is out of the frame. 
The Offset is when the baby head is out of the frame least 0.5 s

To set the Offset, use the same rules for mechanics as with the Onset. 
Hit #5-STOP and then hit “JUMP-BACK-BY” to go back to the timestamp that is just before the head exits the frame. 
Then JOG forward by hitting #3-JOGFORWARD until you reach the Offset of that cell. 
If you go too far, you can JOG backward by hitting #1-JOGBACK. 
You will likely have to hit the JOG keys numerous times. 
If you feel that you have either jumped too far back or went too far forward, hold the JOG keys to move in either direction a bit faster.

Hit ???? to create the Offset

### Create babyangle column

run the ??? script to create a new column for babyangle

## momangle

`<momangle_f-s-o-u-d-b>`

### General Orientation

This code captures the viewing angle of the face (front, side, oblique, up, down, back) of the mom.

Coders are watching/tagging each of these events by marking onset/offset times for the duration of head angle.

### Value List

`f` = front

`s` = side profile

`o` = oblique

`u` = up

`d` = down

`b` = back

### Operational Definitions

`<f>` Code “f” for a front view of the face, when mom or baby has 2 eyes, nose, mouth in view

`<s>` Code "s" for a side view of the face, when mom or baby shows one eye, profile of nose, one ear. 1 hemisphere of head. 

`<o>` Code "o" for an oblique view of the face, when mom or baby has one ear (may be obscured by hair), one full eye, one partial eye (this is between side view and front view, ~3/4 face)

`<u>` Code "u" for looking up view of the face, when mom or baby shows the jaw line, underneath of nose, partial eyes

`<d>` Code "d" for looking down view of the face, when mom or baby shows forehead, hairline, eyebrows, bridge of nose, Maybe not whole nose

`<b>` Code "b" for back of head view, when mom or baby head is in the frame, but shows no facial features (eye, nose, lip) maybe ear only

### How to Code

Set “JUMP-BACK-BY” key to 1 s.

Enable cell highlighting.

Watch in real time for the mom's movement.

Watch mom's head.

## babyangle

`<babyangle_f-s-o-u-d-b>`

### General Orientation

This code captures the viewing angle of the face (front, side, oblique, up, down, back) of the baby. 

Coders are watching/tagging each of these events by marking onset/offset times for the duration of head angle.

### Value List

`f` = front

`s` = side profile

`o` = oblique

`u` = up

`d` = down

`b` = back

### Operational Definitions

`<f>` Code “f” for a front view of the face, when mom or baby has 2 eyes, nose, mouth in view

`<s>` Code "s" for a side view of the face, when mom or baby shows one eye, profile of nose, one ear. 1 hemisphere of head. 

`<o>` Code "o" for an oblique view of the face, when mom or baby has one ear (may be obscured by hair), one full eye, one partial eye (this is between side view and front view, ~3/4 face)

`<u>` Code "u" for looking up view of the face, when mom or baby shows the jaw line, underneath of nose, partial eyes

`<d>` Code "d" for looking down view of the face, when mom or baby shows forehead, hairline, eyebrows, bridge of nose, Maybe not whole nose

`<b>` Code "b" for back of head view, when mom or baby head is in the frame, but shows no facial features (eye, nose, lip) maybe ear only

### How to Code

Set “JUMP-BACK-BY” key to 1 s.

Enable cell highlighting.

Watch in real time for the baby's movement.

Watch baby's head.




# Delete from here to end

Set “JUMP-BACK-BY” key to 1 s.

Enable cell highlighting.

Watch in real time for the baby's movement.

Watch baby's feet and knees.

As soon as you see baby's foot/knee lift up off of the ground; hit #5-STOP and then hit “JUMP-BACK-BY” to go back to the timestamp that is just before the lift. 
Then JOG forward by hitting #3-JOGFORWARD until you reach the Onset of that cell. 
If you go too far, you can JOG backward by hitting #1-JOGBACK. You will likely have to hit the JOG keys numerous times. 
If you feel that you have either jumped too far back or went too far forward, hold the JOG keys to move in either direction a bit faster. Hit ENTER to create a new cell at this Onset.

Now, watch in real time to see when the baby stops moving. 
The Offset is when the baby stops moving for at least 0.5 s (the pause has to look and feel like an actual pause when you are watching in real time; don't simply end a bout of locomotion because there was a 0.5-s pause, especially if it looks like the baby is about to take another step). 
The first frame when the foot/knee stops moving or when the foot settles into its final position (sometimes infants stop their walking bout on their tip-toes) is the offset. 
The same applies to sliding steps.

To set the Offset, use the same rules for mechanics as with the onset. Hit #5-STOP and then hit “JUMP-BACK-BY” to go back to the timestamp that is just before the lift. 
Then JOG forward by hitting #3-JOGFORWARD until you reach the Offset of that cell. 
If you go to far, you can JOG backward by hitting #1-JOGBACK. You will likely have to hit the JOG keys numerous times. 
If you feel that you have either jumped too far back or went too far forward, hold the JOG buttons to move in either direction a bit faster.

## Delete from here down

`<babyhead_b>`

### General Orientation

This code captures the times that mom is engaged in locomotion or fell.

Bouts of locomotion are scored as events, where the gray spaces between cells mean the mom is stationary.

Coders are watching/tagging each of these events by marking onset/offset times for the duration of locomotion bouts

Coders are watching for steps with the feet, the knees, or the bum.
Any other movements that are not initiated from these three body locations is considered to be a transition between postures and is subsumed by stationary, as it is not locomotion.

Bouts that are coded as “.” means that mom is off camera or her legs are off camera, and coder cannot see or infer whether mom is stationary or moving.


### How to Code

Set “JUMP-BACK-BY” key to 1 s.

Enable cell highlighting on the controller.

Watch in real time for the mom's movement.

Watch for the feet and knees.

As soon as you see mom's foot/knee lift up off of the ground; hit #5-STOP and then hit “JUMP-BACK-BY” to go back to the timestamp that is just before the lift. 
Then JOG forward by hitting #3-JOGFORWARD until you reach the onset of that cell. If you go too far, you can JOG backward by hitting #1-JOGBACK. 
If you feel that you have either jumped too far back or went too far forward, hold the JOG keys to move in either direction a bit faster. 
Hit ENTER to create a new cell at this Onset.

Now, watch in real time to see when the mom stops moving. 
The Offset is when the mom stops moving for at least 0.5 s (the pause has to look and feel like an actual pause when you are watching in real time; don't simply end a bout of locomotion because there was a 0.5-s pause, especially if it looks like the mom is about to take another step). 
The first frame when the foot/knee stops moving or when the foot settles into its final position is the offset. The same applies to sliding steps.

To set the Offset, use the same rules for mechanics as with the Onset. 
Hit #5-STOP and then hit “JUMP-BACK-BY” to go back to the timestamp that is just before the lift. 
Then JOG forward by hitting #3-JOGFORWARD until you reach the Offset of that cell. 
If you go too far, you can JOG backward by hitting #1-JOGBACK. 
You will likely have to hit the JOG keys numerous times. 
If you feel that you have either jumped too far back or went too far forward, hold the JOG keys to move in either direction a bit faster.